name: Playit Setup and Keep Alive

on:
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  setup_and_keep_alive:
    runs-on: windows-latest # or a specific Windows version

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Download and Install Playit
        shell: powershell
        run: |
          Invoke-WebRequest -Uri "https://github.com/playit-cloud/playi..." -OutFile "$env:USERPROFILE\playit.exe"
          Start-Sleep -Seconds 5  # Give some time for the download to complete

      - name: Enable TS (Remote Desktop)
        shell: powershell
        run: |
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -name "fDenyTSConnections" -Value 0
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
          Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "admin@123" -Force)

      - name: Run playit
        shell: powershell
        env:
          PLAYIT_AUTH_KEY: ${{ secrets.PL }}
        run: |
          Start-Process -FilePath "$env:USERPROFILE\playit.exe" -ArgumentList "--secret $env:PLAYIT_AUTH_KEY" -NoNewWindow -Wait
          Start-Process -FilePath "$env:USERPROFILE\playit.exe" -NoNewWindow

      - name: Keep the GitHub Action Runner Alive
        shell: bash
        run: |
          sleep 21600 # Keep the runner alive for 6 hours
